# Generated by Django 5.2.6 on 2025-09-11 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rotinas_automaticas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AtivosPrecosBruto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_ativo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("data_referencia", models.DateField(blank=True, null=True)),
                (
                    "preco_abertura",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "preco_maximo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "preco_minimo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "preco_medio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "preco_ultimo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "preco_oferta_compra",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "preco_oferta_venda",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "volume_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("quantidade_total", models.BigIntegerField(blank=True, null=True)),
                ("numero_negocios", models.IntegerField(blank=True, null=True)),
                ("fonte", models.CharField(default="B3", max_length=20)),
                ("data_carga", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Preços de Ativos (Bruto)",
                "verbose_name_plural": "Preços de Ativos (Bruto)",
                "db_table": "ativosprecos",
            },
        ),
        migrations.CreateModel(
            name="CanalDivulgacaoCompanhia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnpj_companhia", models.CharField(max_length=20)),
                ("denominacao_social", models.CharField(max_length=200)),
                ("endereco_canal", models.CharField(max_length=500)),
                ("tipo_canal", models.CharField(max_length=100)),
                ("data_referencia", models.DateField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Canal de Divulgação",
                "verbose_name_plural": "Canais de Divulgação",
                "db_table": "rotinas_automaticas_canaldivulgacaocompanhia",
            },
        ),
        migrations.CreateModel(
            name="CompanhiaAberta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnpj", models.CharField(max_length=20)),
                ("denominacao_social", models.CharField(max_length=200)),
                ("denominacao_comercial", models.CharField(max_length=200)),
                ("setor_atividade", models.CharField(max_length=100)),
                ("classificacao_setor", models.CharField(max_length=100)),
                ("situacao", models.CharField(max_length=50)),
                ("data_registro", models.DateField(blank=True, null=True)),
                ("data_referencia", models.DateField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Companhia Aberta",
                "verbose_name_plural": "Companhias Abertas",
                "db_table": "rotinas_automaticas_companhiaaberta",
            },
        ),
        migrations.CreateModel(
            name="ControleRotina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("ativo", models.BooleanField(default=True)),
                ("hora_execucao", models.TimeField()),
                ("periodo", models.CharField(max_length=50)),
                ("executar_inicio", models.BooleanField(default=False)),
                ("ultima_execucao", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Controle de Rotina",
                "verbose_name_plural": "Controles de Rotinas",
                "db_table": "rotinas_automaticas_controlerotina",
            },
        ),
        migrations.CreateModel(
            name="CvmGeralFii",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnpj_fundo", models.CharField(max_length=20)),
                ("denominacao_social", models.CharField(max_length=200)),
                ("tipo_fundo", models.CharField(max_length=100)),
                ("segmento_atuacao", models.CharField(max_length=100)),
                ("administrador", models.CharField(max_length=200)),
                ("gestor", models.CharField(max_length=200)),
                ("situacao", models.CharField(max_length=50)),
                ("data_registro", models.DateField(blank=True, null=True)),
                ("data_referencia", models.DateField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CVM Geral FII",
                "verbose_name_plural": "CVM Geral FII",
                "db_table": "rotinas_automaticas_cvmgeralfii",
            },
        ),
        migrations.CreateModel(
            name="FundoListadoB3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20)),
                ("razao_social", models.CharField(max_length=300)),
                ("cnpj", models.CharField(max_length=14)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fundo Listado B3",
                "verbose_name_plural": "Fundos Listados B3",
                "db_table": "rotinas_automaticas_fundolistadob3",
            },
        ),
        migrations.CreateModel(
            name="StatusExecucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
                ("descricao", models.CharField(max_length=255)),
                ("icone", models.CharField(max_length=10)),
                ("cor", models.CharField(max_length=7)),
            ],
            options={
                "verbose_name": "Status de Execução",
                "verbose_name_plural": "Status de Execuções",
                "db_table": "rotinas_automaticas_statusexecucao",
            },
        ),
        migrations.CreateModel(
            name="TipoRotina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("icone", models.CharField(max_length=50)),
                ("cor", models.CharField(max_length=7)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de Rotina",
                "verbose_name_plural": "Tipos de Rotinas",
                "db_table": "rotinas_automaticas_tiporotina",
            },
        ),
        migrations.CreateModel(
            name="ValorMobiliarioCompanhia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnpj_companhia", models.CharField(max_length=20)),
                ("denominacao_social", models.CharField(max_length=200)),
                ("cod_cvm", models.CharField(max_length=20)),
                ("tipo_valor_mobiliario", models.CharField(max_length=100)),
                ("mercado", models.CharField(max_length=50)),
                ("segmento", models.CharField(max_length=100)),
                ("data_referencia", models.DateField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Valor Mobiliário da Companhia",
                "verbose_name_plural": "Valores Mobiliários das Companhias",
                "db_table": "rotinas_automaticas_valormobiliariocompanhia",
            },
        ),
        migrations.CreateModel(
            name="HistoricoExecucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                ("iniciado_em", models.DateTimeField()),
                ("finalizado_em", models.DateTimeField(blank=True, null=True)),
                ("duracao_segundos", models.IntegerField(blank=True, null=True)),
                ("saida_stdout", models.TextField(default="")),
                ("saida_stderr", models.TextField(default="")),
                ("codigo_retorno", models.IntegerField(blank=True, null=True)),
                ("argumentos_executados", models.CharField(default="", max_length=500)),
                ("ambiente", models.CharField(default="", max_length=50)),
                ("servidor", models.CharField(default="", max_length=100)),
                (
                    "rotina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rotinas_automaticas.controlerotina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Execução",
                "verbose_name_plural": "Históricos de Execuções",
                "db_table": "rotinas_automaticas_historicoexecucao",
            },
        ),
        migrations.CreateModel(
            name="MonitorRotina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_atual", models.CharField(max_length=20)),
                ("ultima_execucao", models.DateTimeField(blank=True, null=True)),
                ("proxima_execucao", models.DateTimeField(blank=True, null=True)),
                ("total_execucoes", models.IntegerField(default=0)),
                ("execucoes_sucesso", models.IntegerField(default=0)),
                ("execucoes_erro", models.IntegerField(default=0)),
                ("duracao_media", models.FloatField(blank=True, null=True)),
                ("duracao_ultima", models.IntegerField(blank=True, null=True)),
                ("alertas_ativo", models.BooleanField(default=False)),
                ("max_duracao_alerta", models.IntegerField(blank=True, null=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "rotina",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rotinas_automaticas.controlerotina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monitor de Rotina",
                "verbose_name_plural": "Monitores de Rotinas",
                "db_table": "rotinas_automaticas_monitorrotina",
            },
        ),
        migrations.CreateModel(
            name="OrcamentoDomestico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custos_fixos", models.DecimalField(decimal_places=2, max_digits=15)),
                ("prazer", models.DecimalField(decimal_places=2, max_digits=15)),
                ("conforto", models.DecimalField(decimal_places=2, max_digits=15)),
                ("metas", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "liberdade_financeira",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("conhecimento", models.DecimalField(decimal_places=2, max_digits=15)),
                ("data", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Orçamento Doméstico",
                "verbose_name_plural": "Orçamentos Domésticos",
                "db_table": "organizesee_orcamentodomestico",
            },
        ),
        migrations.CreateModel(
            name="OrcamentoDomesticoDividas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=20)),
                ("descricao", models.CharField(max_length=255)),
                ("valor_mensal", models.DecimalField(decimal_places=2, max_digits=15)),
                ("quantidade_parcelas", models.IntegerField()),
                (
                    "taxa_juros",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "valor_hoje",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("divida_total", models.DecimalField(decimal_places=2, max_digits=15)),
                ("juros_mensais", models.DecimalField(decimal_places=2, max_digits=15)),
                ("flag", models.BooleanField()),
                ("data_cadastro", models.DateTimeField()),
                ("mes", models.IntegerField()),
                ("ano", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dívida - Orçamento Doméstico",
                "verbose_name_plural": "Dívidas - Orçamento Doméstico",
                "db_table": "orcamentoDomestico_Dividas",
            },
        ),
        migrations.CreateModel(
            name="OrcamentoDomesticoEntradas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=20)),
                ("descricao", models.CharField(max_length=255)),
                ("valor_mensal", models.DecimalField(decimal_places=2, max_digits=15)),
                ("flag", models.BooleanField()),
                ("data_cadastro", models.DateTimeField()),
                ("mes", models.IntegerField()),
                ("ano", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada - Orçamento Doméstico",
                "verbose_name_plural": "Entradas - Orçamento Doméstico",
                "db_table": "orcamentoDomestico_Entradas",
            },
        ),
        migrations.CreateModel(
            name="OrcamentoDomesticoGastos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=20)),
                ("descricao", models.CharField(max_length=255)),
                ("valor_mensal", models.DecimalField(decimal_places=2, max_digits=15)),
                ("flag", models.BooleanField()),
                ("data_cadastro", models.DateTimeField()),
                ("mes", models.IntegerField()),
                ("ano", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto - Orçamento Doméstico",
                "verbose_name_plural": "Gastos - Orçamento Doméstico",
                "db_table": "orcamentoDomestico_Gastos",
            },
        ),
        migrations.CreateModel(
            name="OrcamentoDomesticoMetasPersonalizadas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo_da_meta", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("valor_hoje", models.DecimalField(decimal_places=2, max_digits=15)),
                ("valor_alvo", models.DecimalField(decimal_places=2, max_digits=15)),
                ("data_limite", models.DateField()),
                ("categoria", models.CharField(max_length=100)),
                ("data_cadastro", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta Personalizada - Orçamento Doméstico",
                "verbose_name_plural": "Metas Personalizadas - Orçamento Doméstico",
                "db_table": "orcamentoDomestico_MetasPersonalizadas",
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8)),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("is_used", models.BooleanField(default=False)),
                ("attempts", models.IntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Redefinição de Senha",
                "verbose_name_plural": "Tokens de Redefinição de Senha",
                "db_table": "organizesee_passwordresettoken",
            },
        ),
        migrations.CreateModel(
            name="RotinaDefinicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("nome_exibicao", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                ("comando_management", models.CharField(max_length=200)),
                ("argumentos_padrao", models.CharField(max_length=500)),
                ("periodo_cron", models.CharField(max_length=50)),
                ("fuso_horario", models.CharField(max_length=50)),
                ("ativo", models.BooleanField(default=True)),
                ("executar_no_inicio", models.BooleanField(default=False)),
                ("timeout_segundos", models.IntegerField(default=3600)),
                ("max_tentativas", models.IntegerField(default=3)),
                ("delay_entre_tentativas", models.IntegerField(default=60)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo_rotina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rotinas_automaticas.tiporotina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Definição de Rotina",
                "verbose_name_plural": "Definições de Rotinas",
                "db_table": "rotinas_automaticas_rotinadefinicao",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_paid_user", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "google_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("google_first_login", models.DateTimeField(blank=True, null=True)),
                ("google_id", models.CharField(blank=True, max_length=255, null=True)),
                ("google_last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "google_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "google_picture",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("google_verified_email", models.BooleanField(default=False)),
                ("is_google_account", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuário",
                "verbose_name_plural": "Perfis de Usuários",
                "db_table": "organizesee_userprofile",
            },
        ),
    ]
