# Generated by Django 5.2.6 on 2025-09-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rotinas_automaticas",
            "0002_ativosprecosbruto_canaldivulgacaocompanhia_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroExecucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_arquivo_processo",
                    models.CharField(
                        help_text="Nome do job/arquivo/processo", max_length=255
                    ),
                ),
                (
                    "tabela_destino",
                    models.CharField(
                        help_text="Tabela destino dos dados carregados", max_length=255
                    ),
                ),
                (
                    "registros_totais_novos",
                    models.IntegerField(
                        default=0, help_text="Quantidade de registros novos inseridos"
                    ),
                ),
                (
                    "quantidade_linhas_arquivo",
                    models.IntegerField(
                        default=0,
                        help_text="Quantidade de linhas do arquivo processado",
                    ),
                ),
                (
                    "registros_totais_arquivo",
                    models.IntegerField(
                        default=0, help_text="Total de registros válidos no arquivo"
                    ),
                ),
                (
                    "registros_totais_atualizados",
                    models.IntegerField(
                        default=0, help_text="Quantidade de registros atualizados"
                    ),
                ),
                (
                    "registros_totais_ignorados",
                    models.IntegerField(
                        default=0, help_text="Quantidade de registros ignorados"
                    ),
                ),
                (
                    "status_execucao",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO", "Aguardando execução"),
                            ("AGENDADA", "Agendada para executar"),
                            ("EXECUTANDO", "Executando"),
                            ("CONCLUIDA", "Concluída com sucesso"),
                            ("ERRO", "Erro"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="AGUARDANDO",
                        max_length=20,
                    ),
                ),
                (
                    "dia_horario_execucao",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data e hora de início da execução"
                    ),
                ),
                (
                    "dia_horario_finalizacao",
                    models.DateTimeField(
                        blank=True, help_text="Data e hora de finalização", null=True
                    ),
                ),
                (
                    "sistema",
                    models.CharField(
                        choices=[
                            ("B3", "B3"),
                            ("CVM", "CVM"),
                            ("MANUAIS", "Manuais"),
                            ("IBGE", "IBGE"),
                        ],
                        help_text="Sistema origem dos dados",
                        max_length=20,
                    ),
                ),
                (
                    "grupo",
                    models.CharField(
                        choices=[
                            ("DIARIO", "Diário"),
                            ("EVENTUAL", "Eventual"),
                            ("MENSAL", "Mensal"),
                            ("ANUAL", "Anual"),
                        ],
                        help_text="Grupo de execução",
                        max_length=20,
                    ),
                ),
                (
                    "proxima_execucao",
                    models.DateTimeField(
                        blank=True, help_text="Próxima execução agendada", null=True
                    ),
                ),
                (
                    "arquivo_log",
                    models.TextField(
                        blank=True,
                        help_text="Caminho do arquivo de log gerado",
                        null=True,
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, help_text="Observações sobre a execução", null=True
                    ),
                ),
                (
                    "erro_detalhes",
                    models.TextField(
                        blank=True, help_text="Detalhes do erro (se houver)", null=True
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Registro de Execução",
                "verbose_name_plural": "Registros de Execução",
                "db_table": "rotinas_automaticas_registro_execucao",
                "ordering": ["-dia_horario_execucao"],
            },
        ),
    ]
