# Generated by Django 5.2.6 on 2025-09-16 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rotinas_automaticas", "0003_registroexecucao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CargaDiariaRotinas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_carga",
                    models.DateField(help_text="Data da carga diária", unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INICIADA", "Iniciada"),
                            ("CONCLUIDA", "Concluída"),
                            ("ERRO", "Erro"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="INICIADA",
                        max_length=20,
                    ),
                ),
                ("total_rotinas_processadas", models.IntegerField(default=0)),
                ("total_rotinas_adicionadas_fila", models.IntegerField(default=0)),
                ("total_rotinas_ignoradas", models.IntegerField(default=0)),
                ("iniciado_em", models.DateTimeField(auto_now_add=True)),
                ("finalizado_em", models.DateTimeField(blank=True, null=True)),
                ("duracao_segundos", models.IntegerField(blank=True, null=True)),
                (
                    "arquivo_log",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("erro_detalhes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Carga Diária de Rotinas",
                "verbose_name_plural": "Cargas Diárias de Rotinas",
                "db_table": "rotinas_automaticas_cargadiariarotinas",
                "ordering": ["-data_carga"],
            },
        ),
        migrations.CreateModel(
            name="FilaExecucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_execucao",
                    models.DateField(help_text="Data planejada para execução"),
                ),
                (
                    "horario_execucao",
                    models.TimeField(help_text="Horário planejado para execução"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("EXECUTANDO", "Executando"),
                            ("CONCLUIDA", "Concluída"),
                            ("ERRO", "Erro"),
                            ("CANCELADA", "Cancelada"),
                            ("RECOVERY", "Em Recovery"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                (
                    "prioridade",
                    models.IntegerField(
                        help_text="Prioridade na fila (copiado do scheduler)"
                    ),
                ),
                ("iniciado_em", models.DateTimeField(blank=True, null=True)),
                ("finalizado_em", models.DateTimeField(blank=True, null=True)),
                ("duracao_segundos", models.IntegerField(blank=True, null=True)),
                ("tentativa_atual", models.IntegerField(default=1)),
                ("max_tentativas", models.IntegerField(default=3)),
                ("ultima_tentativa_em", models.DateTimeField(blank=True, null=True)),
                ("codigo_retorno", models.IntegerField(blank=True, null=True)),
                ("saida_stdout", models.TextField(blank=True, null=True)),
                ("saida_stderr", models.TextField(blank=True, null=True)),
                ("erro_detalhes", models.TextField(blank=True, null=True)),
                (
                    "arquivo_processado",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("registros_processados", models.IntegerField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fila de Execução",
                "verbose_name_plural": "Fila de Execução",
                "db_table": "rotinas_automaticas_filaexecucao",
                "ordering": ["data_execucao", "horario_execucao", "prioridade"],
            },
        ),
        migrations.CreateModel(
            name="GrupoDiasExecucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        choices=[
                            ("DIARIO", "Diário (Segunda a Domingo)"),
                            ("DIAS_SEMANA", "Dias de Semana (Segunda a Sexta)"),
                            ("FINAL_SEMANA", "Final de Semana (Sábado e Domingo)"),
                            ("D_MAIS_1", "D+1 (Terça a Sábado)"),
                            ("PERSONALIZADO", "Personalizado"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
                ("segunda", models.BooleanField(default=False)),
                ("terca", models.BooleanField(default=False)),
                ("quarta", models.BooleanField(default=False)),
                ("quinta", models.BooleanField(default=False)),
                ("sexta", models.BooleanField(default=False)),
                ("sabado", models.BooleanField(default=False)),
                ("domingo", models.BooleanField(default=False)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Grupo de Dias de Execução",
                "verbose_name_plural": "Grupos de Dias de Execução",
                "db_table": "rotinas_automaticas_grupodiasexecucao",
            },
        ),
        migrations.CreateModel(
            name="LogScheduler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                (
                    "componente",
                    models.CharField(
                        help_text="Componente que gerou o log", max_length=100
                    ),
                ),
                ("mensagem", models.TextField()),
                (
                    "dados_extra",
                    models.JSONField(
                        blank=True, help_text="Dados extras em JSON", null=True
                    ),
                ),
                ("stack_trace", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "carga_diaria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rotinas_automaticas.cargadiariarotinas",
                    ),
                ),
                (
                    "fila_execucao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rotinas_automaticas.filaexecucao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log do Scheduler",
                "verbose_name_plural": "Logs do Scheduler",
                "db_table": "rotinas_automaticas_logscheduler",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="SchedulerRotina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_execucao",
                    models.CharField(
                        choices=[
                            ("DIARIO", "Diário"),
                            ("MENSAL", "Mensal"),
                            ("EVENTUAL", "Eventual"),
                            ("CICLICO", "Cíclico"),
                        ],
                        default="DIARIO",
                        max_length=20,
                    ),
                ),
                (
                    "tipo_rotina",
                    models.CharField(
                        choices=[
                            ("CARGA_ARQUIVO", "Carga de Arquivo"),
                            ("DOWNLOAD_ARQUIVO", "Download de Arquivo"),
                            ("EXECUCAO_SCRIPT", "Execução de Script"),
                            ("CHAMADA_API", "Chamada API"),
                            ("COMANDO_SISTEMA", "Comando do Sistema"),
                        ],
                        default="CARGA_ARQUIVO",
                        max_length=20,
                    ),
                ),
                (
                    "ciclico",
                    models.BooleanField(
                        default=False, help_text="Executa a cada X horas"
                    ),
                ),
                (
                    "intervalo_horas",
                    models.IntegerField(
                        default=1, help_text="Intervalo em horas para execução cíclica"
                    ),
                ),
                (
                    "executar",
                    models.BooleanField(default=True, help_text="Deve ser executada"),
                ),
                (
                    "horario_execucao",
                    models.TimeField(help_text="Horário de execução (formato HH:MM)"),
                ),
                (
                    "endpoint_url",
                    models.CharField(
                        blank=True,
                        help_text="URL do endpoint para chamada",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "metodo_http",
                    models.CharField(
                        choices=[("GET", "GET"), ("POST", "POST"), ("PUT", "PUT")],
                        default="POST",
                        max_length=10,
                    ),
                ),
                (
                    "payload_json",
                    models.TextField(
                        blank=True, help_text="JSON do payload para envio", null=True
                    ),
                ),
                (
                    "headers_json",
                    models.TextField(
                        blank=True, help_text="Headers HTTP em JSON", null=True
                    ),
                ),
                (
                    "mascara_arquivo",
                    models.CharField(
                        blank=True,
                        help_text="Máscara do arquivo (ex: TradeInfo*20250910*.csv)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "pasta_origem",
                    models.CharField(
                        blank=True,
                        help_text="Pasta de origem dos arquivos",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "permite_recovery",
                    models.BooleanField(
                        default=True, help_text="Permite recuperação em caso de falha"
                    ),
                ),
                (
                    "max_tentativas_recovery",
                    models.IntegerField(
                        default=3, help_text="Máximo de tentativas de recuperação"
                    ),
                ),
                (
                    "delay_recovery_minutos",
                    models.IntegerField(
                        default=5,
                        help_text="Delay entre tentativas de recovery (minutos)",
                    ),
                ),
                (
                    "prioridade",
                    models.IntegerField(
                        default=50,
                        help_text="Prioridade na fila (menor número = maior prioridade)",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grupo_dias",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rotinas_automaticas.grupodiasexecucao",
                    ),
                ),
                (
                    "rotina_definicao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduler",
                        to="rotinas_automaticas.rotinadefinicao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduler de Rotina",
                "verbose_name_plural": "Scheduler de Rotinas",
                "db_table": "rotinas_automaticas_schedulerrotina",
                "ordering": ["prioridade", "horario_execucao"],
            },
        ),
        migrations.AddField(
            model_name="filaexecucao",
            name="scheduler_rotina",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rotinas_automaticas.schedulerrotina",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="filaexecucao",
            unique_together={("scheduler_rotina", "data_execucao", "horario_execucao")},
        ),
    ]
