# Generated by Django 5.2.6 on 2025-09-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rotinas_automaticas",
            "0004_cargadiariarotinas_filaexecucao_grupodiasexecucao_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargadiariarotinas",
            name="status",
            field=models.CharField(
                choices=[
                    ("INICIADA", "Iniciada"),
                    ("CONCLUIDA", "Concluída"),
                    ("ERRO", "Erro"),
                    ("CANCELADA", "Cancelada"),
                    ("SUBSTITUIDA", "Substituída"),
                ],
                default="INICIADA",
                max_length=20,
            ),
        ),
    ]
